/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package COMPONENT;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author huuho
 */
public class PanelMucSP extends javax.swing.JPanel {

    /**
     * Creates new form PanelMucSP
     */
    String TitlemucSP = "null";

    public PanelMucSP() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D graphics2D = (Graphics2D) g.create();
        graphics2D.setColor(new Color(0, 102, 102));
        graphics2D.fillRect(0, 0, getWidth(), 20);
        graphics2D.setColor(Color.white);
        graphics2D.setFont(new Font("SansSerif", Font.BOLD, 15));
        graphics2D.drawString(TitlemucSP, 0, 16);
        int demension_Y = 280;
        int demension_X = 845;
        int count = this.getComponentCount();
        while (count > 6) {
            count -= 6;
            demension_Y += 260;
        }
        setPreferredSize(new Dimension(demension_X, demension_Y));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(0, 0));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 5);
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);
    }// </editor-fold>//GEN-END:initComponents

    public String getTitlemucSP() {
        return TitlemucSP;
    }

    public void setTitlemucSP(String TitlemucSP) {
        this.TitlemucSP = TitlemucSP;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
